# This is a basic workflow to help you get started with Actions

name: frontend-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "candidate-assessment" ]
    paths:
      - 'country-flags-app-main/**'
  pull_request:
    branches: [ "main", "candidate-assessment" ]
    paths:
      - 'country-flags-app-main/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  frontend-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install -g yarn

      - name: Install
        run: yarn install

      - name: Run Lint
        run: yarn lint --quiet

      - name: Run Test
        run: yarn run test:coverage
