
name: frontend-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "candidate-assessment" ]
    paths:
      - 'country-flags-app-main/**'
      - '.github/**'
  pull_request:
    branches: [ "main", "candidate-assessment" ]
    paths:
      - 'country-flags-app-main/**'
      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  frontend-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Sonarcloud
    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: country-flags-app-main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn
        working-directory: country-flags-app-main

      - name: Install Dependencies
        run: yarn install
        working-directory: country-flags-app-main
        

      - name: Yarn Build
        run: yarn build
        working-directory: country-flags-app-main

      - name: SonarCube Scan
        uses: sonarsource/sonarcloud-github-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: country-flags-app-main/src
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
            -Dsonar.javascript.lcov.reportPaths=./country-flags-app-main/coverage/lcov.info
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.qualitygate.wait=true
            -Dsonar.verbose=true

      - name: Run Lint
        continue-on-error: true
        run: yarn lint --quiet
        working-directory: country-flags-app-main

      - name: Run Test
        run: yarn run test:coverage
        working-directory: country-flags-app-main
      

